---
title: "Social Media Platform Tracker"
author: "Owen Bernstein"
date: "6/2/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

options(scipen = 30)

library(gt)
library(broom)
library(skimr)
library(lubridate)
library(janitor)
library(dotwhisker)
library(tidytext)
library(ggthemes)
library(webshot)
library(latticeExtra)
library(ggrepel)
library(tidyverse)
```

```{r}

# Reading data from CSV of Google sheet and then only taking rows that have
# data

tracker_data <- read_csv("raw-data/tracker_data.csv") %>% 
  clean_names() %>% 
  select(company, date, type, community_help:coronavirus, key_development) %>% 
  slice(1:442)

# Creating pivoted tracker data to work more easily with tags

tracker_pivot <- tracker_data %>% 
  pivot_longer(community_help:coronavirus, names_to = "policy",
               values_to = "true")

# Reading in Covid Us Data

covid_data <- read_csv("raw-data/covid_data.csv") %>% 
  clean_names()

# Creating change Covid data that has new US cases by day

change_covid_data <- covid_data %>% 
  filter(country_region == "us_dif") %>% 
  pivot_longer(x1_22_2020:x7_13_2020, names_to = "date", names_prefix = "x",
               values_to = "cases") %>% 
  mutate(date = mdy(date)) %>% 
  select(date, cases)

# Creating covid_world_change that has new World cases by day

covid_world_change  <- covid_data %>% 
  filter(country_region == "world_dif") %>% 
  pivot_longer(x1_22_2020:x7_13_2020, names_to = "date", names_prefix = "x",
               values_to = "cases") %>% 
  mutate(date = mdy(date)) %>% 
  select(date, cases)

# Creating tag data. This has the number of each type of update for each
# company

tag_data <- tracker_pivot %>% 
  select(-key_development) %>% 
  na.omit() %>% 
  group_by(company, policy) %>% 
  count(true) %>% 
  ungroup() %>% 
  filter(true == "Yes")
  
```

```{r}

# Creating total updates data. Includes the total number of updates for each
# company

total_updates <- tracker_data %>% 
  select(company) %>% 
  count(company) %>% 
  arrange(desc(n))

# Graph of number of updates by company

totals_graph <- total_updates %>% 
  ggplot(aes(x = reorder(company, -n), n)) +
  geom_bar(stat = "identity") +
  labs(title = "Number of Updates in 2020 by Social Media Platform", x = "",
       y = "Number of Updates") +
  theme_fivethirtyeight() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

totals_graph

# Graph of quantity of each type of update by comapny

type_graph <- tag_data %>% 
  filter(company == "Google" | company == "Facebook" | company == "TikTok") %>% 
  mutate(policy = recode(policy, community_help = "Community Help",
                         information = "Information",
                         coronavirus = "Coronavirus",
                         advertisement = "Advertisements",
                         content_regulation = "Content Regulation",
                         privacy = "Privacy",
                         misinformation = "Misinformation")) %>% 
  ggplot(aes(fill = company, x = reorder(policy, -n), y = n)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(title = "Social Media Platforms' Updates by Content Category", x = "",
       y = "Number of Updates", fill = "") +
  theme_fivethirtyeight() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

type_graph

# Graph of percent of each type of update by company

percent_type_graph_1 <- tag_data %>% 
  filter(company == "Google" | company == "Facebook" | company == "TikTok" |
           company == "LinkedIn") %>% 
  mutate(policy = recode(policy, community_help = "Community Help",
                         information = "Information", 
                         coronavirus = "Coronavirus",
                         advertisement = "Advertisements",
                         content_regulation = "Content Regulation",
                         privacy = "Privacy",
                         misinformation = "Misinformation")) %>% 
  group_by(company) %>% 
  mutate(perc_type = n/sum(n) * 100) %>% 
  ggplot(aes(fill = company, x = reorder(policy, -perc_type), y = perc_type)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(title = "Social Media Platforms' Updates by Type (Percent)", x = "",
       y = "Percent of Updates", fill = "") +
  theme_fivethirtyeight() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

percent_type_graph_2 <- tag_data %>% 
  filter(company == "Twitter" | company == "Apple" | company == "Instagram" |
           company == "LinkedIn" | company == "Youtube") %>% 
  mutate(policy = recode(policy, community_help = "Community Help",
                         information = "Information", 
                         coronavirus = "Coronavirus",
                         advertisement = "Advertisements",
                         content_regulation = "Content Regulation",
                         privacy = "Privacy",
                         misinformation = "Misinformation")) %>% 
  group_by(company) %>% 
  mutate(perc_type = n/sum(n) * 100) %>% 
  ggplot(aes(fill = company, x = reorder(policy, -perc_type), y = perc_type)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(title = "Social Media Platforms' Updates by Type (Percent)", x = "",
       y = "Percent of Updates", fill = "") +
  theme_fivethirtyeight() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

percent_type_graph_3 <- tag_data %>% 
  filter(company == "Reddit" | company == "WhatsApp" | company == "Pinterest" |
           company == "Snapchat" | company == "Nextdoor") %>% 
  mutate(policy = recode(policy, community_help = "Community Help",
                         information = "Information", 
                         coronavirus = "Coronavirus",
                         advertisement = "Advertisements",
                         content_regulation = "Content Regulation",
                         privacy = "Privacy",
                         misinformation = "Misinformation")) %>% 
  group_by(company) %>% 
  mutate(perc_type = n/sum(n) * 100) %>% 
  ggplot(aes(fill = company, x = reorder(policy, -perc_type), y = perc_type)) +
  geom_bar(position = "dodge", stat = "identity") +
  labs(title = "Social Media Platforms' Updates by Type (Percent)", x = "",
       y = "Percent of Updates", fill = "") +
  theme_fivethirtyeight() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

percent_type_graph_1
percent_type_graph_2
percent_type_graph_3
```

```{r}

# Creating updates time which is the number of updates per week

updates_time <- tracker_data %>%
  mutate(date = mdy(date)) %>%
  mutate(date = floor_date(date, "1 week")) %>%
  count(date) %>% 
  slice(2:27)

us_covid_week <- change_covid_data %>%
  mutate(date = floor_date(date, "1 week")) %>%
  group_by(date) %>% 
  summarise(sum(cases))

# Left joining change covid data and updates time by date. This results in the
# number of updates in the week and the number of new cases in the US on the
# last day of the week. (Should change to average new cases for the week)

plat_covid_data <- left_join(updates_time, us_covid_week, by = "date") %>% 
  replace_na(list('sum(cases)' = 0)) %>% 
  rename(cases = 'sum(cases)', updates = n)
  

# Creating plot of new platform updates and a plot new US COVID-19 cases over
# time. then combining the plots on a double y axis plot

plat_time <- xyplot(updates ~ date, plat_covid_data, type = "l" , lwd=2,
                    col="steelblue", ylab = "", xlab = "",
                    main="New US Covid-19 Cases and Platform Updates by Week")

cov_time <- xyplot(cases ~ date, plat_covid_data, type = "l", lwd=2,
                   col='pink',
                   main="New US Covid-19 Cases and Platform Updates by Week",
                   xlab = "Date", ylab = "New US COVID-19 Cases")
 
double_y_graph <- doubleYScale(plat_time, cov_time,
                               use.style= FALSE, text = c("New Platform Updates",
                                                          "New COVID-19 Cases"))

double_y_graph
```
```{r}

# Creating updates time which is the number of updates per week

updates_time <- tracker_data %>%
  mutate(date = mdy(date)) %>%
  mutate(date = floor_date(date, "1 week")) %>%
  count(date) %>% 
  slice(2:27)

world_covid_week <- covid_world_change %>%
  mutate(date = floor_date(date, "1 week")) %>%
  group_by(date) %>% 
  summarise(sum(cases))

# Left joining change covid data and updates time by date. This results in the
# number of updates in the week and the number of new cases in the US on the
# last day of the week. (Should change to average new cases for the week)

plat_covid_data <- left_join(updates_time, world_covid_week, by = "date") %>% 
  replace_na(list('sum(cases)' = 0)) %>% 
  rename(cases = 'sum(cases)', updates = n)
  

# Creating plot of new platform updates and a plot new US COVID-19 cases over
# time. then combining the plots on a double y axis plot

plat_time <- xyplot(updates ~ date, plat_covid_data, type = "l" , lwd=2,
                    col="steelblue", ylab = "", xlab = "",
                    main="New Global Covid-19 Cases and Platform Updates by Week")

cov_time <- xyplot(cases ~ date, plat_covid_data, type = "l", lwd=2,
                   col='pink',
                   main="New Global Covid-19 Cases and Platform Updates by Week",
                   xlab = "Date", ylab = "New World COVID-19 Cases")
 
double_y_graph <- doubleYScale(plat_time, cov_time,
                               use.style= FALSE, text = c("New Platform Updates",
                                                          "New Global COVID-19 Cases" ))

double_y_graph
```


```{r}

# Creating a graph of the total updates of each company by their monthly active
# users

update_mau <- total_updates %>% 
  mutate(mau = c(2000, 800, 2498, 2000, 386, 1400, 1000, 260, 330, 2000, 366,
                 398, 27)) %>% 
  ggplot(aes(mau, n)) +
  geom_point() +
  geom_smooth(method = "glm") +
  labs(title = "Number of Updates by Monthly Active Users",
       x = "Monthly Active Users (Millions)", y = "Number of Updates") +
  theme_minimal() +
  geom_label_repel(aes(label = as.character(company)), size = 2.6,
                  box.padding   = 0.8, 
                  point.padding = 0.3,
                  color = "black")

update_mau
```





